# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\yu_python\yu_工具开发_2018\yu_rename\main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 500)
        MainWindow.setMinimumSize(QtCore.QSize(600, 500))
        MainWindow.setMaximumSize(QtCore.QSize(600, 500))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralWidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 601, 321))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 330, 601, 171))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_qingkong = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_qingkong.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_qingkong.setObjectName("btn_qingkong")
        self.gridLayout_2.addWidget(self.btn_qingkong, 5, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.btn_rename = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_rename.setObjectName("btn_rename")
        self.gridLayout_2.addWidget(self.btn_rename, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1)
        self.btn_kuozhanming = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_kuozhanming.setObjectName("btn_kuozhanming")
        self.gridLayout_2.addWidget(self.btn_kuozhanming, 4, 2, 1, 1)
        self.btn_tihuan = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_tihuan.setObjectName("btn_tihuan")
        self.gridLayout_2.addWidget(self.btn_tihuan, 1, 2, 1, 1)
        self.btn_charu = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_charu.setObjectName("btn_charu")
        self.gridLayout_2.addWidget(self.btn_charu, 2, 2, 1, 1)
        self.btn_daxiaoxie = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_daxiaoxie.setObjectName("btn_daxiaoxie")
        self.gridLayout_2.addWidget(self.btn_daxiaoxie, 3, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.le_new_name = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.le_new_name.setObjectName("le_new_name")
        self.horizontalLayout.addWidget(self.le_new_name)
        self.cb_add = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.cb_add.setChecked(True)
        self.cb_add.setObjectName("cb_add")
        self.horizontalLayout.addWidget(self.cb_add)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.sb_start = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.sb_start.setProperty("value", 1)
        self.sb_start.setObjectName("sb_start")
        self.horizontalLayout.addWidget(self.sb_start)
        self.sb_step = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.sb_step.setProperty("value", 1)
        self.sb_step.setObjectName("sb_step")
        self.horizontalLayout.addWidget(self.sb_step)
        self.sb_weishu = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.sb_weishu.setProperty("value", 2)
        self.sb_weishu.setObjectName("sb_weishu")
        self.horizontalLayout.addWidget(self.sb_weishu)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.sb_charuweizhi = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.sb_charuweizhi.setObjectName("sb_charuweizhi")
        self.horizontalLayout_3.addWidget(self.sb_charuweizhi)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.le_charuneirong = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.le_charuneirong.setObjectName("le_charuneirong")
        self.horizontalLayout_3.addWidget(self.le_charuneirong)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.le_chazhao = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.le_chazhao.setObjectName("le_chazhao")
        self.horizontalLayout_2.addWidget(self.le_chazhao)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.le_tihuan = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.le_tihuan.setObjectName("le_tihuan")
        self.horizontalLayout_2.addWidget(self.le_tihuan)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.le_old_kuozhanname = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.le_old_kuozhanname.setObjectName("le_old_kuozhanname")
        self.horizontalLayout_5.addWidget(self.le_old_kuozhanname)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.le_new_kuozhanname = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.le_new_kuozhanname.setObjectName("le_new_kuozhanname")
        self.horizontalLayout_5.addWidget(self.le_new_kuozhanname)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 4, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cb_kaitou_s = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.cb_kaitou_s.setObjectName("cb_kaitou_s")
        self.horizontalLayout_4.addWidget(self.cb_kaitou_s)
        self.cb_all_s = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.cb_all_s.setObjectName("cb_all_s")
        self.horizontalLayout_4.addWidget(self.cb_all_s)
        self.cb_kaitou_b = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.cb_kaitou_b.setObjectName("cb_kaitou_b")
        self.horizontalLayout_4.addWidget(self.cb_kaitou_b)
        self.cb_all_b = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.cb_all_b.setObjectName("cb_all_b")
        self.horizontalLayout_4.addWidget(self.cb_all_b)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 1, 1, 1)
        self.btn_zhixing = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_zhixing.setObjectName("btn_zhixing")
        self.gridLayout_2.addWidget(self.btn_zhixing, 5, 1, 1, 1)
        self.btn_baoliuzhongwen = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btn_baoliuzhongwen.setObjectName("btn_baoliuzhongwen")
        self.gridLayout_2.addWidget(self.btn_baoliuzhongwen, 5, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_qingkong.setText(_translate("MainWindow", "清空"))
        self.label_11.setText(_translate("MainWindow", "扩展名"))
        self.label_9.setText(_translate("MainWindow", "插入"))
        self.btn_rename.setText(_translate("MainWindow", "重命名"))
        self.label_6.setText(_translate("MainWindow", "重命名"))
        self.label_2.setText(_translate("MainWindow", "查找"))
        self.label_10.setText(_translate("MainWindow", "大小写"))
        self.btn_kuozhanming.setText(_translate("MainWindow", "扩展名"))
        self.btn_tihuan.setText(_translate("MainWindow", "替换"))
        self.btn_charu.setText(_translate("MainWindow", "插入"))
        self.btn_daxiaoxie.setText(_translate("MainWindow", "大小写"))
        self.label_14.setText(_translate("MainWindow", "主文件名"))
        self.cb_add.setText(_translate("MainWindow", "增加位数"))
        self.label_7.setText(_translate("MainWindow", "开始/增量/位数"))
        self.label_8.setText(_translate("MainWindow", "插入位置"))
        self.label_13.setText(_translate("MainWindow", "插入内容"))
        self.label_4.setText(_translate("MainWindow", "查找"))
        self.label_3.setText(_translate("MainWindow", "替换"))
        self.label_5.setText(_translate("MainWindow", "查找"))
        self.label_12.setText(_translate("MainWindow", "替换"))
        self.cb_kaitou_s.setText(_translate("MainWindow", "开头小写"))
        self.cb_all_s.setText(_translate("MainWindow", "全部小写"))
        self.cb_kaitou_b.setText(_translate("MainWindow", "开头大写"))
        self.cb_all_b.setText(_translate("MainWindow", "全部大写"))
        self.btn_zhixing.setText(_translate("MainWindow", "执行"))
        self.btn_baoliuzhongwen.setText(_translate("MainWindow", "保留中文"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

